application:
  name: software-metadata
  port: 8080

database:
  uri: ${MONGO_URI:mongodb://localhost:27017/mydb}
  name: software_metadata
  collections: ## software_type: collection_name
    docker-container: docker-container
    jupyter-notebook: jupyter-notebook
    singularity-container: singularity-container

oci:
  labels:
    mappings:
      annotations: annotations
      metadata: org.opencadc.image.metadata
      digest: Digest
  default:
    resource:
      cores:
        min: 5
        max: 15
      memory:
        min: 3
        max: 9