database:
  uri: ${MONGO_URI:mongodb://localhost:27017/mydb}
  name: software_metadata
  collections:
    canfar-oci-images: canfar-oci-images
    docker-container: docker-container
    jupyter-notebook: jupyter-notebook
