apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: core
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: core
    spec:
      containers:
      - image: {{ .Values.image_registry_url }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        name: ska-src-mm-image-discovery-api-core
        ports:
        - containerPort: 8080
        resources: {}
        livenessProbe:
          httpGet:
            path: /v1/ping
            port: 8080
      restartPolicy: Always
      serviceAccountName: ""
status: {}
