apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.deployment.namespace }}
  labels:
  {{- toYaml .Values.deployment.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
    {{- toYaml .Values.deployment.labels | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
      {{- toYaml .Values.deployment.labels | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.deployment.image_registry_url }}:{{ .Values.deployment.image_tag }}
          imagePullPolicy: Always
          name: ska-src-mm-image-discovery-api-core
          env:
            - name: MONGO_URI
              value: {{ .Values.deployment.mongodb.uri }}
          ports:
            - containerPort: 8080
          resources: {}
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8080
      restartPolicy: Always

