image: docker:git
services:
- docker:dind

stages:
  - test

test:
  stage: test
  script:
    - apk add --no-cache python3 py3-pip
    - python3 -m pip install -r requirements.txt --break-system-packages
    - python3 -m pytest --junitxml=report.xml -v
  artifacts:
    when: on_success
    paths:
      - report.xml
    expire_in: 30 days
    reports:
      junit: report.xml
