image: docker:git
services:
  - docker:dind

stages:
  - test

test-service:
  image:
    name: openjdk:21-jdk-slim
    entrypoint: [ "" ]
  stage: test
  script:
    - export JAVA_HOME=/usr/local/openjdk-21
    - ./mvnw dependency:go-offline
    - ./mvnw test