image: docker:git
services:
- docker:dind

stages:
- test

test-init:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  stage: test
  script:
    - apk add --no-cache python3 py3-pip bash make
    - python3 -m pip install jinjanator --break-system-packages
    - make init API_NAME=test
    - cd ../ska-src-test-api && docker-compose up -d
    - docker exec test-core /bin/bash -c "cd src && python3 -m pytest ../tests"