image: docker:git
services:
- docker:dind

stages:
  - test

unit-tests:
  stage: test
  script:
    - apk add --no-cache python3 py3-pip
    - python3 -m pip install -r requirements.txt --break-system-packages
    - python3 -m pytest --junitxml=reports/unit-tests.xml -v
  artifacts:
    when: always
    paths:
      - report.xml
    expire_in: 30 days
    reports:
      junit: reports/unit-tests.xml
