repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        stages: [pre-commit]
        types: [python]
        pass_filenames: false
        always_run: true
        verbose: true
