# First stage: Build the native image
FROM openjdk:21-jdk-slim

# Set the working directory
WORKDIR /app

# Copy Maven configuration and download dependencies
COPY pom.xml .
COPY mvnw .
COPY .mvn ./.mvn
RUN ./mvnw dependency:go-offline

# Copy the application source code
COPY src/main ./src/main

# Compile the native image, skipping tests for faster build
RUN ./mvnw package -DskipTests

# Expose the port for the application
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "/app/target/ska-src-mm-image-discovery-0.0.1.jar"]