version: "3.5"
services:
  ska-src-mm-image-discovery-api:
    container_name: ska-src-mm-image-discovery-api
    image: ska-src-mm-image-discovery-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment: { }
    ports:
      - "8080:8080"
