version: "3.5"
services:
  ska-src-mm-image-discovery-api:
    container_name: ska-src-mm-image-discovery-api
    image: ska-src-mm-image-discovery-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: src
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/?authSource=admin
    ports:
      - "8080:8080"
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=metadata_db
    volumes:
      - mongodb_data:/data/db
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network: