version: "3.5"
services:
  core:
    container_name: mm-image-discovery-core
    image: mm-image-discovery-core:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment: { }
    ports:
      - 8080:8080
