version: "3.5"
services:
  core:
    container_name: mm-image-discovery-core
    image: mm-image-discovery-core:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISABLE_AUTHENTICATION: "yes"
      API_ROOT_PATH:
      API_SCHEME: http
      IAM_CLIENT_CONF_URL: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
      API_IAM_CLIENT_ID: some-uuid
      API_IAM_CLIENT_SECRET:
      API_IAM_CLIENT_SCOPES: openid profile
      API_IAM_CLIENT_AUDIENCE: mm-image-discovery-api
      PERMISSIONS_API_URL: https://permissions.srcdev.skao.int/api/v1
      PERMISSIONS_SERVICE_NAME: mm-image-discovery-api
      PERMISSIONS_SERVICE_VERSION: 1
    ports:
      - 8080:8080
