# First stage: Build the native image
FROM ghcr.io/graalvm/native-image-community:21


# Set the working directory
WORKDIR /usr/src/app

# Copy Maven configuration and download dependencies
COPY pom.xml .
COPY mvnw .
COPY .mvn ./.mvn
RUN ./mvnw dependency:go-offline

# Copy the application source code
COPY src/main ./src/main

# Compile the native image, skipping tests for faster build
RUN ./mvnw -Pnative native:compile -DskipTests

# Expose the port for the application
EXPOSE 8080

# Run the application
ENTRYPOINT ["/usr/src/app/target/ska-src-mm-image-discovery"]
