apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ivoa.service: mm_image_discovery
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      ivoa.service: mm_image_discovery
  strategy: {}
  template:
    metadata:
      labels:
        ivoa.service: mm_image_discovery
    spec:
      containers:
        image: {{ .Values.image_registry_url }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        name: ska-src-mm-image-discovery
        ports:
        - containerPort: 8080
        resources: {}
        livenessProbe:
          httpGet:
            path: /v1/ping
            port: 8080
      restartPolicy: Always
      serviceAccountName: ""
status: {}
