apiVersion: v1
kind: Service
metadata:
  labels:
    ivoa.service: mm_image_discovery
  name: core
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    ivoa.service: mm_image_discovery
status:
  loadBalancer: {}
