apiVersion: v1
kind: Service
metadata:
  labels:
    ivoa.service: "mm-image-discovery"
  name: mm-image-discovery
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: http-default
    port: 80
    targetPort: 8080
  selector:
    ivoa.service: "mm-image-discovery"
